### ISSUE TITLE
Finalize the theme colors

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/fcsc-web#11]

**Comment by LayanJay** [comment]
In tailwindcss we can enable the JIT (Just in Time) mode until the theme colors finalized. For example, if we want to use #c12344 color we can simply use bg-[#c12344] or text-[#c12344] like that. Even in the production mode, this works. But not recommended for production. It's better to finalize and declare the theme in the tailwindcss.config before we deploy to the production.
